"""cleaned

Revision ID: 3ee22dd8706b
Revises: 4fd67d470c1e
Create Date: 2022-06-16 21:52:11.995295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee22dd8706b'
down_revision = '4fd67d470c1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
